version: 0.0
os: linux
files:
  - source: /backend
    destination: /home/ubuntu/expressit/backend # Path on your EC2 instance for backend code
  - source: /scripts
    destination: /home/ubuntu/expressit/scripts # Path on your EC2 instance for deployment scripts

hooks:
  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 300
      runas: ubuntu
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
      runas: ubuntu