version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/ExpressIt  # ✅ unchanged, set by you

hooks:
  BeforeInstall:
    - location: script/before_install.sh  # ✅ changed: was `scripts`, now `script`
      timeout: 300
      runas: root

  ApplicationStop:
    - location: script/app_stop.sh  # ✅ changed: was `scripts`, now `script`
      timeout: 60
      runas: root

  ApplicationStart:
    - location: script/app_start.sh  # ✅ changed: was `scripts`, now `script`
      timeout: 120
      runas: root