version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 22
    commands:
      - echo Installing backend dependencies...
      - cd backend
      - npm install
      - echo Installing frontend dependencies...
      - cd ../frontend
      - npm install

  build:
    commands:
      - echo Building Vite frontend...
      - npm run build
      - echo Copying Vite build to backend/public...
      - mkdir -p ../backend/public
      - cp -r dist/* ../backend/public/

  post_build:
    commands:
      - echo Build completed on date
      - cd ../backend
      - cp ../appspec.yml .
      - cp -r ../scripts .
      # optional cleanup
      # - npm prune --production

artifacts:
  base-directory: backend
  files:
    - '**/*'
