version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18 # IMPORTANT: Change to your Node.js version (e.g., 16, 20). Match what you tested with locally.
    commands:
      - echo "Installing frontend dependencies..."
      - cd frontend # Navigate into your frontend directory
      - npm install # Install frontend dependencies
      - cd .. # Go back to the repository root

      - echo "Installing backend dependencies..."
      - cd backend # Navigate into your backend directory
      - npm install # Install backend dependencies
      - cd .. # Go back to the repository root

  build:
    commands:
      - echo "Building frontend (Vite)..."
      - cd frontend
      - npm run build # This command runs your Vite build
      - cd ..

      - echo "Backend has no specific build step, ensuring dependencies are in place."
      - # Node.js backends typically don't have a 'build' command like frontends.

  post_build:
    commands:
      - echo "Build completed successfully."

artifacts:
  files:
    - '**/*' # This tells CodeBuild to include ALL files from the repository in the output artifact
  base-directory: . # The root of your repository is the base for the artifact
  discard-paths: no # Keep the original directory structure (frontend/, backend/, etc.)