version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - echo Installing dependencies...
      - cd backend
      - npm install
      - cd ../frontend
      - npm install
  build:
    commands:
      - echo Building React frontend...
      - npm run build
      - echo Copying build to backend/public...
      - mkdir -p ../backend/public
      - cp -r build/* ../backend/public/
  post_build:
    commands:
      - echo Build completed on `date`
      - cd ../backend
      - cp ../appspec.yml .
      - cp -r ../scripts .

artifacts:
  files:
    - '**/*'
  base-directory: backend
